// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjT-XeoSGtMgNI6mA_kTKEnlfMmHazn3U',
    appId: '1:518712046700:web:1b1614d72ddfdacf1fd449',
    messagingSenderId: '518712046700',
    projectId: 'finkin-credential',
    authDomain: 'finkin-credential.firebaseapp.com',
    storageBucket: 'finkin-credential.appspot.com',
    measurementId: 'G-WLQTXGRKQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfhA3bRTAG0Mo8K4u49J5zW_JZuM6p1qw',
    appId: '1:518712046700:android:98969fa10eba96531fd449',
    messagingSenderId: '518712046700',
    projectId: 'finkin-credential',
    storageBucket: 'finkin-credential.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCngKdGtq-hqcYh6Twyw8HwpSp09E7RdEI',
    appId: '1:518712046700:ios:7ca4c79e5cccedee1fd449',
    messagingSenderId: '518712046700',
    projectId: 'finkin-credential',
    storageBucket: 'finkin-credential.appspot.com',
    iosBundleId: 'com.example.demoAgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCngKdGtq-hqcYh6Twyw8HwpSp09E7RdEI',
    appId: '1:518712046700:ios:69e2fb67995b2b601fd449',
    messagingSenderId: '518712046700',
    projectId: 'finkin-credential',
    storageBucket: 'finkin-credential.appspot.com',
    iosBundleId: 'com.example.demoAgent.RunnerTests',
  );
}
